package az.tribe.lifeplanner.ui.habit

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import az.tribe.lifeplanner.data.network.AiProxyService
import az.tribe.lifeplanner.domain.enum.Mood
import az.tribe.lifeplanner.domain.model.Goal
import az.tribe.lifeplanner.domain.model.Habit
import co.touchlab.kermit.Logger
import com.adamglin.PhosphorIcons
import com.adamglin.phosphoricons.Regular
import com.adamglin.phosphoricons.regular.Sparkle
import com.adamglin.phosphoricons.regular.X
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.*

/**
 * Quick reflection bottom sheet shown after habit check-in with AI-generated content
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
internal fun QuickReflectionBottomSheet(
    habit: Habit,
    linkedGoal: Goal?,
    aiProxy: AiProxyService,
    onDismiss: () -> Unit,
    onSave: (String, String, Mood) -> Unit
) {
    var title by remember { mutableStateOf("Reflection: ${habit.title}") }
    var content by remember { mutableStateOf("") }
    var selectedMood by remember { mutableStateOf(Mood.NEUTRAL) }
    var isGenerating by remember { mutableStateOf(false) }
    var hasGenerated by remember { mutableStateOf(false) }
    val coroutineScope = rememberCoroutineScope()

    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)

    // Generate AI reflection when mood changes (after first selection)
    LaunchedEffect(selectedMood) {
        if (!hasGenerated) return@LaunchedEffect
        isGenerating = true
        try {
            val aiContent = generateAiReflection(
                aiProxy = aiProxy,
                habit = habit,
                linkedGoal = linkedGoal,
                mood = selectedMood
            )
            if (aiContent != null) {
                title = aiContent.first
                content = aiContent.second
            }
        } catch (e: Exception) {
            // Fallback to simple content
            content = "Completed ${habit.title}. Feeling ${selectedMood.emoji}"
        }
        isGenerating = false
    }

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        dragHandle = null,
        containerColor = MaterialTheme.colorScheme.surface,
        shape = RoundedCornerShape(topStart = 24.dp, topEnd = 24.dp)
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .navigationBarsPadding()
        ) {
            // Header with AI icon
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp, vertical = 16.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Text(
                            "Quick Reflection",
                            style = MaterialTheme.typography.titleLarge,
                            fontWeight = FontWeight.Bold
                        )
                        // AI sparkle icon
                        Icon(
                            imageVector = PhosphorIcons.Regular.Sparkle,
                            contentDescription = "AI Generated",
                            tint = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.size(20.dp)
                        )
                    }
                    Text(
                        "How was your ${habit.title}?",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    linkedGoal?.let {
                        Text(
                            "Linked to: ${it.title}",
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.primary
                        )
                    }
                }
                IconButton(onClick = onDismiss) {
                    Icon(
                        imageVector = PhosphorIcons.Regular.X,
                        contentDescription = "Close"
                    )
                }
            }

            // Mood selector
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp)
            ) {
                Text(
                    "How are you feeling?",
                    style = MaterialTheme.typography.labelLarge,
                    fontWeight = FontWeight.Medium
                )

                Spacer(modifier = Modifier.height(12.dp))

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceEvenly
                ) {
                    Mood.entries.sortedBy { it.score }.forEach { mood ->
                        MoodOption(
                            mood = mood,
                            isSelected = mood == selectedMood,
                            onClick = {
                                selectedMood = mood
                                // Trigger AI generation on first mood selection
                                if (!hasGenerated) {
                                    hasGenerated = true
                                    isGenerating = true
                                    coroutineScope.launch {
                                        try {
                                            val aiContent = generateAiReflection(
                                                aiProxy = aiProxy,
                                                habit = habit,
                                                linkedGoal = linkedGoal,
                                                mood = mood
                                            )
                                            if (aiContent != null) {
                                                title = aiContent.first
                                                content = aiContent.second
                                            }
                                        } catch (e: Exception) {
                                            content = "Completed ${habit.title}. Feeling ${mood.emoji}"
                                        }
                                        isGenerating = false
                                    }
                                }
                            }
                        )
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // AI Generated Title
            OutlinedTextField(
                value = title,
                onValueChange = { title = it },
                label = {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        Text("Title")
                        if (hasGenerated) {
                            Icon(
                                imageVector = PhosphorIcons.Regular.Sparkle,
                                contentDescription = "AI",
                                modifier = Modifier.size(14.dp),
                                tint = MaterialTheme.colorScheme.primary
                            )
                        }
                    }
                },
                singleLine = true,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp),
                shape = RoundedCornerShape(12.dp),
                enabled = !isGenerating
            )

            Spacer(modifier = Modifier.height(12.dp))

            // Content input with loading state
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp)
                    .height(140.dp)
            ) {
                OutlinedTextField(
                    value = content,
                    onValueChange = { content = it },
                    label = {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(4.dp)
                        ) {
                            Text("Your reflection")
                            if (hasGenerated) {
                                Icon(
                                    imageVector = PhosphorIcons.Regular.Sparkle,
                                    contentDescription = "AI",
                                    modifier = Modifier.size(14.dp),
                                    tint = MaterialTheme.colorScheme.primary
                                )
                            }
                        }
                    },
                    placeholder = {
                        Text(
                            if (!hasGenerated) "Select a mood to generate AI reflection..."
                            else "How did it go? Any insights?"
                        )
                    },
                    modifier = Modifier.fillMaxSize(),
                    shape = RoundedCornerShape(12.dp),
                    maxLines = 5,
                    enabled = !isGenerating
                )

                // Loading overlay
                if (isGenerating) {
                    Box(
                        modifier = Modifier
                            .fillMaxSize()
                            .background(MaterialTheme.colorScheme.surface.copy(alpha = 0.7f)),
                        contentAlignment = Alignment.Center
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            CircularProgressIndicator(
                                modifier = Modifier.size(20.dp),
                                strokeWidth = 2.dp
                            )
                            Text(
                                "Generating reflection...",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Action buttons
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                OutlinedButton(
                    onClick = onDismiss,
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Text("Skip")
                }

                Button(
                    onClick = {
                        val finalTitle = title.ifBlank { "Reflection: ${habit.title}" }
                        val finalContent = content.ifBlank {
                            "Completed ${habit.title}. Feeling ${selectedMood.emoji}"
                        }
                        onSave(finalTitle, finalContent, selectedMood)
                    },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp),
                    enabled = !isGenerating
                ) {
                    Text("Save")
                }
            }

            Spacer(modifier = Modifier.height(24.dp))
        }
    }
}

/**
 * Generate AI reflection content based on habit, goal, and mood
 */
internal suspend fun generateAiReflection(
    aiProxy: AiProxyService,
    habit: Habit,
    linkedGoal: Goal?,
    mood: Mood
): Pair<String, String>? = withContext(Dispatchers.IO) {
    try {
        val prompt = buildString {
            append("Generate a short, personal journal reflection (2-3 sentences) for someone who just completed their habit.\n\n")
            append("Habit: ${habit.title}\n")
            append("Description: ${habit.description}\n")
            append("Current streak: ${habit.currentStreak} days\n")
            append("Total completions: ${habit.totalCompletions}\n")
            append("Mood: ${mood.displayName} (${mood.emoji})\n")

            linkedGoal?.let {
                append("\nThis habit is linked to their goal: ${it.title}\n")
                append("Goal progress: ${(it.progress ?: 0).toInt()}%\n")
                append("Goal status: ${it.status}\n")
            }

            append("\nWrite in first person, be encouraging and reflective. Match the tone to their ${mood.displayName.lowercase()} mood.")
            append("\nAlso suggest a better, more personal title for this reflection (not just 'Reflection: habit name').")
        }

        val schema = buildJsonObject {
            put("type", "object")
            putJsonObject("properties") {
                putJsonObject("title") { put("type", "string") }
                putJsonObject("content") { put("type", "string") }
            }
            putJsonArray("required") { add("title"); add("content") }
        }

        val responseText = aiProxy.generateStructuredJson(prompt, schema)

        val json = Json { ignoreUnknownKeys = true }
        val parsed = json.parseToJsonElement(responseText).jsonObject
        val aiTitle = parsed["title"]?.jsonPrimitive?.content ?: "Reflection: ${habit.title}"
        val aiContent = parsed["content"]?.jsonPrimitive?.content ?: ""
        Pair(aiTitle, aiContent)
    } catch (e: Exception) {
        Logger.e("HabitTrackerScreen") { "AI habit reflection generation failed: ${e.message}" }
        null
    }
}
