package az.tribe.lifeplanner.domain.model

import kotlinx.datetime.LocalDate
import kotlinx.datetime.LocalDateTime
import kotlinx.serialization.Serializable

/**
 * Represents a periodic review report generated by AI
 */
@Serializable
data class ReviewReport(
    val id: String,
    val type: ReviewType,
    val periodStart: LocalDate,
    val periodEnd: LocalDate,
    val generatedAt: LocalDateTime,
    val summary: String,
    val highlights: List<ReviewHighlight>,
    val insights: List<ReviewInsight>,
    val recommendations: List<ReviewRecommendation>,
    val stats: ReviewStats,
    val feedback: ReviewFeedback? = null,
    val isRead: Boolean = false
)

/**
 * Type of review period
 */
@Serializable
enum class ReviewType {
    WEEKLY,
    MONTHLY,
    QUARTERLY,
    YEARLY
}

/**
 * A highlight/achievement from the review period
 */
@Serializable
data class ReviewHighlight(
    val id: String,
    val title: String,
    val description: String,
    val category: HighlightCategory,
    val relatedGoalId: String? = null,
    val iconType: String = "star"
)

/**
 * Categories for highlights
 */
@Serializable
enum class HighlightCategory {
    GOAL_COMPLETED,
    MILESTONE_REACHED,
    STREAK_ACHIEVED,
    HABIT_CONSISTENCY,
    XP_MILESTONE,
    LEVEL_UP,
    NEW_BADGE,
    PERSONAL_BEST
}

/**
 * An insight derived from the user's data
 */
@Serializable
data class ReviewInsight(
    val id: String,
    val title: String,
    val description: String,
    val type: InsightType,
    val dataPoint: String? = null,
    val trend: TrendDirection? = null
)

/**
 * Types of insights
 */
@Serializable
enum class InsightType {
    PRODUCTIVITY_PATTERN,
    STRENGTH_AREA,
    IMPROVEMENT_AREA,
    HABIT_CORRELATION,
    TIME_MANAGEMENT,
    CONSISTENCY,
    CATEGORY_FOCUS
}

/**
 * Trend direction for insights
 */
@Serializable
enum class TrendDirection {
    UP,
    DOWN,
    STABLE
}

/**
 * A recommendation for the next period
 */
@Serializable
data class ReviewRecommendation(
    val id: String,
    val title: String,
    val description: String,
    val actionType: RecommendationAction,
    val priority: RecommendationPriority,
    val relatedGoalId: String? = null
)

/**
 * Types of recommended actions
 */
@Serializable
enum class RecommendationAction {
    CREATE_GOAL,
    ADJUST_GOAL,
    CREATE_HABIT,
    FOCUS_CATEGORY,
    TAKE_BREAK,
    INCREASE_DIFFICULTY,
    REDUCE_SCOPE,
    CELEBRATE,
    REFLECT
}

/**
 * Priority levels for recommendations
 */
@Serializable
enum class RecommendationPriority {
    HIGH,
    MEDIUM,
    LOW
}

/**
 * Statistics for the review period
 */
@Serializable
data class ReviewStats(
    val goalsCompleted: Int,
    val goalsInProgress: Int,
    val milestonesCompleted: Int,
    val habitsTracked: Int,
    val habitCompletionRate: Float,
    val journalEntries: Int,
    val xpEarned: Int,
    val streakDays: Int,
    val mostActiveCategory: String?,
    val totalActiveMinutes: Int = 0,
    val comparisonToPrevious: StatsComparison? = null
)

/**
 * Comparison to previous period
 */
@Serializable
data class StatsComparison(
    val goalsCompletedDiff: Int,
    val habitCompletionRateDiff: Float,
    val xpEarnedDiff: Int,
    val overallTrend: TrendDirection
)

/**
 * User feedback on the review
 */
@Serializable
data class ReviewFeedback(
    val rating: FeedbackRating,
    val comment: String? = null,
    val submittedAt: LocalDateTime
)

/**
 * Feedback rating options
 */
@Serializable
enum class FeedbackRating {
    HELPFUL,
    NOT_HELPFUL,
    NEUTRAL
}

/**
 * Summary card shown on home screen
 */
@Serializable
data class ReviewSummaryCard(
    val reviewId: String,
    val type: ReviewType,
    val periodLabel: String,
    val headline: String,
    val quickStats: List<QuickStat>,
    val isNew: Boolean
)

/**
 * Quick stat for summary card
 */
@Serializable
data class QuickStat(
    val label: String,
    val value: String,
    val trend: TrendDirection? = null
)
