package az.tribe.lifeplanner.tools

import az.tribe.lifeplanner.domain.service.KnowledgeLibrary
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Writes `supabase/knowledge_lessons.sql` from the lessons bundled in [KnowledgeLibrary], so the
 * Supabase seed is generated from the source of truth rather than transcribed by hand.
 *
 * It is a test only because that is the cheapest way to run Kotlin against the real library. Run it
 * after editing the bundled lessons, then apply the SQL in the Supabase dashboard:
 *
 *     ./gradlew :app:shared:testAndroidHostTest --tests "*KnowledgeSeedGeneratorTest"
 *
 * Editing lessons in Supabase directly is the normal path; this is for re-seeding a fresh project.
 */
class KnowledgeSeedGeneratorTest {

    @Test
    fun `writes the supabase seed`() {
        val sql = buildString {
            appendLine("-- Learn content: the lessons and paths behind the Learn map.")
            appendLine("-- GENERATED by KnowledgeSeedGeneratorTest from KnowledgeLibrary.bundledLessons.")
            appendLine("-- Do not hand-edit this file; edit rows in Supabase, or the bundled list and re-run.")
            appendLine("-- Dashboard -> SQL Editor -> paste & run. Safe to re-run: existing rows are updated.")
            appendLine()
            appendLine(schemaSql())
            appendLine()
            appendLine("-- ============================== Lessons ==============================")
            appendLine()
            KnowledgeLibrary.bundledLessons.forEachIndexed { index, bit ->
                appendLine(
                    "INSERT INTO knowledge_lessons (id, title, body, emoji, min_level, read_min, detail, takeaway, source, topics, sort_order) VALUES (" +
                        "${q(bit.id)}, ${q(bit.title)}, ${q(bit.body)}, ${q(bit.emoji)}, " +
                        "${bit.minLevel}, ${bit.readMin}, ${jsonb(bit.detail)}, ${q(bit.takeaway)}, " +
                        "${qOrNull(bit.source)}, ${jsonb(bit.topics.map { it.name })}, $index)"
                )
                appendLine(
                    "ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body, " +
                        "emoji = EXCLUDED.emoji, min_level = EXCLUDED.min_level, read_min = EXCLUDED.read_min, " +
                        "detail = EXCLUDED.detail, takeaway = EXCLUDED.takeaway, source = EXCLUDED.source, " +
                        "topics = EXCLUDED.topics, sort_order = EXCLUDED.sort_order;"
                )
                appendLine()
            }
            appendLine("-- ============================== Paths ==============================")
            appendLine()
            KnowledgeLibrary.bundledCollections.forEachIndexed { index, c ->
                appendLine(
                    "INSERT INTO knowledge_collections (id, title, subtitle, emoji, lesson_ids, sort_order) VALUES (" +
                        "${q(c.id)}, ${q(c.title)}, ${q(c.subtitle)}, ${q(c.emoji)}, ${jsonb(c.lessonIds)}, $index)"
                )
                appendLine(
                    "ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, " +
                        "emoji = EXCLUDED.emoji, lesson_ids = EXCLUDED.lesson_ids, sort_order = EXCLUDED.sort_order;"
                )
                appendLine()
            }
        }

        assertTrue(KnowledgeLibrary.bundledLessons.isNotEmpty(), "no bundled lessons to seed")

        // Only writes when run from a checkout that actually has supabase/ two levels up (the test
        // runs from app/shared). Anywhere else, including CI, this is a no-op rather than a test
        // that litters the build machine.
        val dir = File("../../supabase")
        if (!dir.isDirectory) {
            println("supabase/ not found at ${dir.absolutePath}, skipping seed write")
            return
        }
        val out = File(dir, "knowledge_lessons.sql")
        out.writeText(sql)
        println("Wrote ${KnowledgeLibrary.bundledLessons.size} lessons to ${out.absolutePath}")
    }

    private fun schemaSql(): String = """
        CREATE TABLE IF NOT EXISTS knowledge_lessons (
            id         TEXT PRIMARY KEY,
            title      TEXT NOT NULL,
            body       TEXT NOT NULL,
            emoji      TEXT NOT NULL DEFAULT '💡',
            min_level  INTEGER NOT NULL DEFAULT 1,
            read_min   INTEGER NOT NULL DEFAULT 2,
            detail     JSONB NOT NULL DEFAULT '[]',
            takeaway   TEXT NOT NULL DEFAULT '',
            source     TEXT,
            topics     JSONB NOT NULL DEFAULT '[]',
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_active  BOOLEAN NOT NULL DEFAULT TRUE,
            updated_at TIMESTAMPTZ DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS knowledge_collections (
            id         TEXT PRIMARY KEY,
            title      TEXT NOT NULL,
            subtitle   TEXT NOT NULL DEFAULT '',
            emoji      TEXT NOT NULL DEFAULT '📚',
            lesson_ids JSONB NOT NULL DEFAULT '[]',
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_active  BOOLEAN NOT NULL DEFAULT TRUE,
            updated_at TIMESTAMPTZ DEFAULT now()
        );

        CREATE INDEX IF NOT EXISTS idx_knowledge_lessons_active ON knowledge_lessons (is_active, sort_order);
        CREATE INDEX IF NOT EXISTS idx_knowledge_collections_active ON knowledge_collections (is_active, sort_order);

        CREATE OR REPLACE FUNCTION set_knowledge_updated_at()
        RETURNS TRIGGER AS ${'$'}${'$'}
        BEGIN NEW.updated_at = now(); RETURN NEW; END;
        ${'$'}${'$'} LANGUAGE plpgsql;

        DROP TRIGGER IF EXISTS trg_knowledge_lessons_updated_at ON knowledge_lessons;
        CREATE TRIGGER trg_knowledge_lessons_updated_at
            BEFORE UPDATE ON knowledge_lessons
            FOR EACH ROW EXECUTE FUNCTION set_knowledge_updated_at();

        DROP TRIGGER IF EXISTS trg_knowledge_collections_updated_at ON knowledge_collections;
        CREATE TRIGGER trg_knowledge_collections_updated_at
            BEFORE UPDATE ON knowledge_collections
            FOR EACH ROW EXECUTE FUNCTION set_knowledge_updated_at();

        -- Lesson content is public: the app fetches it without signing in, so guests get it too.
        ALTER TABLE knowledge_lessons ENABLE ROW LEVEL SECURITY;
        ALTER TABLE knowledge_collections ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS "knowledge_lessons_public_read" ON knowledge_lessons;
        DROP POLICY IF EXISTS "knowledge_lessons_admin_write" ON knowledge_lessons;
        DROP POLICY IF EXISTS "knowledge_collections_public_read" ON knowledge_collections;
        DROP POLICY IF EXISTS "knowledge_collections_admin_write" ON knowledge_collections;

        CREATE POLICY "knowledge_lessons_public_read"
            ON knowledge_lessons FOR SELECT TO anon, authenticated USING (TRUE);
        CREATE POLICY "knowledge_lessons_admin_write"
            ON knowledge_lessons FOR ALL
            USING ((auth.jwt() ->> 'email') = 'admin@lifeplanner.app');

        CREATE POLICY "knowledge_collections_public_read"
            ON knowledge_collections FOR SELECT TO anon, authenticated USING (TRUE);
        CREATE POLICY "knowledge_collections_admin_write"
            ON knowledge_collections FOR ALL
            USING ((auth.jwt() ->> 'email') = 'admin@lifeplanner.app');
    """.trimIndent()

    /** Postgres string literal: single quotes doubled, matching the other seed scripts. */
    private fun q(value: String): String = "'" + value.replace("'", "''") + "'"

    private fun qOrNull(value: String?): String = value?.let { q(it) } ?: "NULL"

    private fun jsonb(values: List<String>): String {
        val array = values.joinToString(",") { "\"" + it.replace("\\", "\\\\").replace("\"", "\\\"") + "\"" }
        return q("[$array]") + "::jsonb"
    }
}
